Project Progress
========================================================

There were 8 main datasets that we are using to visualize in shiny.  Each of the datasets has to be pulled from the census bureau API using the acs package and cleaned.  Given the different ways the data was displayed after grabbing each of the individual tables using the acs package we broke each of the cleaning of the different datasets into individual R scripts.  Overall we are looking at economic, education, age and other demographic variables.

Our Demographic variables:
* Age and sex for each state.
* College attendence broken down by age, gender and state.
* Health insurance enrollment by age and gender.

Our Economic variables:
* Employment status by gender, age and state.
* Povery level by education level, family status and state.
* SNAP/food stamp by race and state.
* Median income by gender, work experience and state.
* Median monthly rent by state.

We have all of the tables pulled from the ACS online API and have largely cleaned these tables into a usuable format.  We are in the stage of choosing plots to display this data.  For most of the variables we will use choropleths and ranking plots.  For our plot of age and gender we have constructed a population pyramid for states.  Below is a population pyramid for the state of Washington.

```{r, echo=FALSE, cache=TRUE, warning=FALSE, message=FALSE}
library(acs)
library(ggplot2)
library(reshape2)
library(plyr)
library(dplyr)
#B01001
# ages 0-4, 5-9, 10-14, *15-19*, *20-24*, 25-29, 30-34, 35-39, 40-44, 45-49,
# 50-54, 55-59, *60-64*, *65-69*, 70-74, 75-79, *80+*
states = geo.make(state = "*")
age = acs.fetch(endyear = 2012, span = 5, geography = states, 
                table.number = "B01001", col.names="pretty")
age.df = data.frame(age@estimate)
names(age.df) = gsub("Sex.by.Age..", "", names(age.df))

age.df = age.df[,-c(1,2,26)]
age.df$state = rownames(age.df)
rownames(age.df) = NULL

age.df$Male..15.to.19.years = age.df[,4] + age.df[,5]
age.df$Female..15.to.19.years = age.df[,27] + age.df[,28]

age.df$Male..20.to.24.years = age.df[,6] + age.df[,7] + age.df[,8]
age.df$Female..20.to.24.years = age.df[,29] + age.df[,30] + age.df[,31]

age.df$Male..60.to.64.years = age.df[,16] + age.df[,17]
age.df$Female..60.to.64.years = age.df[,39] + age.df[,40]

age.df$Male..65.to.69.years = age.df[,18] + age.df[,19]
age.df$Female..65.to.69.years = age.df[,41] + age.df[,42]

age.df = age.df[,-c(4:8, 16:19, 27:31, 39:42)]

age.melt = melt(age.df, id='state')
agecols = ldply(strsplit(as.character(age.melt$variable), "\\.\\."))
names(agecols) = c("gender", "age")
agesex = data.frame(state = age.melt$state, gender = agecols$gender, 
                     age = agecols$age, freq = age.melt$value)
agesex$age = factor(agesex$age, levels(agesex$age)[c(18, 9, 1:8, 10:17)])
levels(agesex$age) = gsub(".years", "", levels(agesex$age))

ggplot(data = subset(agesex, state=="Washington"), aes(x = age, y = freq, fill=gender)) +
  coord_flip() + geom_bar(subset = .(gender=="Female"), stat="identity") +
  geom_bar(subset = .(gender=="Male"), stat="identity", aes(y=-freq))
```

Here is an example of a ranking plot for median income for males who work full time.

```{r2, echo=FALSE, cache=TRUE, warning=FALSE, message=FALSE}
states = geo.make(state = "*")
median = acs.fetch(endyear = 2012, span = 5, geography = states, 
                   table.number = "B19326", col.names="pretty")
med = data.frame(median@estimate)
names(med) = gsub("Median.Income.by.Sex.by.Work.Experience.for.the.Population.15..Years..Median.income.in.the.past.12.months..in.2012.inflation.adjusted.dollars.....", "", names(med))
names(med) = c('total','male_total','male_full','male_other',
                     'female_total','female_full','female_other')
med$state = factor(rownames(med))
rownames(med) = NULL
med$region = tolower(med$state)
states <- map_data("state")
medplot = merge(med,states,by='region')

qplot(male_full, reorder(state, male_full), data=subset(med, state != "Puerto Rico"))
```