source('age.R')
source('foodstamps.R')
source('health.R')
source('jobs.R')
source('poverty.R')
source('university.R')

head(agesextable)
head(foodtable)
head(healthsextable)
head(healthincometable)
head(emptable)
head(povtable)
head(univtable)